name: 'cleanup'

on:
  workflow_dispatch:

jobs:
  set-envs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api graphql -F owner='abcxyz' -F name='access-on-demand' -F pr_number='1410639531' -f query='
            query($name: String!, $owner: String!, $pr_number: String!) {
              repository(owner: $owner, name: $name) {
                pullRequest(number: $number) {
                  reviewDecision
                }
              }
            }
          '
