name: 'aod-note'

on:
  pull_request:
    types:
      - 'opened'
    paths:
      - 'iam.yaml'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-aod-note'
  cancel-in-progress: true

jobs:
  note:
    uses: 'sqin2019/access-on-demand-fork/.github/workflows/note.yml@main' # Change here to pin the tag or commit.
    with:
      expiry_hours: 36
