name: 'create_tag'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The name of the tag to be created.'
        type: 'string'
        required: true
      branch:
        description: 'The branch to create tag from.'
        type: 'string'
        required: false
        default: 'main'
      message:
        description: 'Message for the tag.'
        type: 'string'
        required: false

jobs:
  create_tag:
    permissions:
      contents: 'write'
    uses: 'sqin2019/access-on-demand-fork/.github/workflows/reusable_create_tag.yml@main'
    # uses: 'abcxyz/access-on-demand/.github/workflows/clicleanup.yml@main'
    with:
      branch: '${{ inputs.branch }}'
      tag: '${{ inputs.tag }}'
      message: '${{ inputs.message }}

