name: 'create_tag'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The name of the tag to be created.'
        type: 'string'
        required: true
      branch:
        description: 'The branch to create tag from.'
        type: 'string'
        required: false
        default: 'main'
      message:
        description: 'Message for the tag.'
        type: 'string'
        required: false
      annotated_tag:
        description: 'Whether to create an annotated tag, if false, only a lightweight tag will be created.'
        type: boolean
        default: true
        required: false

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: job summary
        run: |
          echo "### inputs" >> $GITHUB_STEP_SUMMARY
          echo "- tag: ${{ inputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- branch: ${{ inputs.branch }}" >> $GITHUB_STEP_SUMMARY
          echo "- annotated tag: ${{ inputs.annotated_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- message: ${{ inputs.message }}" >> $GITHUB_STEP_SUMMARY

  create_tag:
    needs: 'print-inputs'
    permissions:
      contents: 'write'
    uses: 'sqin2019/access-on-demand-fork/.github/workflows/reusable_create_tag.yml@main'
    # uses: 'abcxyz/access-on-demand/.github/workflows/clicleanup.yml@main'
    with:
      branch: '${{ inputs.branch }}'
      tag: '${{ inputs.tag }}'
      message: '${{ inputs.message }}'
      env: 'void'
      annotated_tag: '${{ inputs.annotated_tag }}'

