name: 'expire_caller'

on:
  workflow_dispatch:

jobs:
  close_pr:
    permissions:
      pull-requests: 'write'
    # uses: 'sqin2019/hello-world/.github/workflows/expire.yml@main'
    uses: 'abcxyz/access-on-demand/.github/workflows/expire.yml@main'
    with:
      repo: 'sqin2019/hello-world'
      expiry_hours: '${{ vars.expiry_hours || 24 }}'
