name: 'aod-iam-handle'
on:
  workflow_call:
    inputs:
      workload_identity_provider:
        description: 'The full identifier of the Workload Identity Provider, including the project number, pool name, and provider name.'
        type: 'string'
        required: true
      service_account:
        description: 'Email address or unique identifier of the Google Cloud service account for which to generate credentials.'
        type: 'string'
        required: true
      go_version:
        description: 'The version of Golang.'
        type: 'string'
        default: '1.20'
        required: false
      aod_cli_version:
        description: 'The version of AOD CLI.'
        type: 'string'
        default: 'latest'
        required: false
      path:
        description: 'IAM request file path. Default is "iam.yaml".'
        type: 'string'
        default: 'iam.yaml'
        required: false

env:
  DEFAULT_DURATION: '2h'

jobs:
  handle:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    name: 'Handle IAM Request'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab' # ratchet:actions/checkout@v3
        with:
          # fetch-depth: 2 # OR "2" -> To retrieve the preceding commit.
          ref: ${{ github.event.pull_request.head.ref }}
      - name: 'tree'
        shell: 'bash'
        run: tree ${{ github.workspace }}
      - name: 'Setup Go'
        uses: 'actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568' # ratchet:actions/setup-go@v3
        with:
          go-version: ${{ inputs.go_version }}
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ inputs.workload_identity_provider }}'
          service_account: '${{ inputs.service_account }}'
          token_format: 'access_token'
      - name: 'Install AOD CLI'
        run: 'go install github.com/abcxyz/access-on-demand/cmd/aod@${{ inputs.aod_cli_version }}'
      # - name: 'install jq'
      #   run: sudo apt-get install -y jq
      # - name: 'versino jq'
      #   run: jq --version
      - name: 'get duration'
        # shell: 'bash'
        run: |
          names='${{ toJson(github.event.pull_request.labels.*.name) }}'
          for name in $(echo "$names" | jq -r '.[]'); do
            if [[ $name == duration-* ]]; then
              IFS='-' read -r part1 part2 <<< "$name"
              echo "LABELED_DURATION=$part2" >> $GITHUB_ENV
              break
            fi
          done
          cat ${{ github.workspace }}/iam.yaml
      - name: 'Run AOD CLI'
        # shell: 'bash'
        env:
          DURATION: '${{ env.DEFAULT_DURATION || env.LABELED_DURATION }}'
          FILE_PATH: ${{ github.workspace }}/${{ inputs.path }}
          START_TIME: ${{ github.event.pull_request.updated_at }}
        run: 'aod iam handle -path $FILE_PATH -duration $DURATION -start-time $START_TIME'
