name: 'release'
on:
  push:
    tags:
      - 'v*'

jobs:
  create-tag:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
    steps:
      - name: 'release'        
        run: |
          echo "done" >> $GITHUB_STEP_SUMMARY
