name: 'set-envs'
on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      wif_provider:
        description: "The first output string"
        value: ${{ jobs.set-envs.outputs.wif_provider }}
      wif_sa:
        description: "The second output string"
        value: ${{ jobs.set-envs.outputs.wif_sa }}

# Assign values to below envs.
env:
  WIF_PROVIDER: 'projects/901968413216/locations/global/workloadIdentityPools/github-pool-299b/providers/github-provider'
  WIF_SERVICE_ACCOUNT: 'pmap-3b39-ci-sa@pmap-ci.iam.gserviceaccount.com'
  # Specify the aod cli version or remove this input to use the latest.
  # AOD_CLI_VERSION:
  # # Specify the go version or remove this input to use the default version 1.20.
  # GO_VERISON:
  # WORKFLOW_SHA: 'main'

jobs:
  set-envs:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      wif_provider: '${{ steps.wif.outputs.WIF_PROVIDER }}'
      wif_sa: '${{ steps.wif.outputs.WIF_SERVICE_ACCOUNT }}'
      # aod_cli_version:
      # go_version:
    steps:
      - id: 'wif'
        run: |
          echo "WIF_PROVIDER=${{ env.WIF_PROVIDER }}" >> "$GITHUB_OUTPUT"
          echo "WIF_SERVICE_ACCOUNT=${{ env.WIF_SERVICE_ACCOUNT }}" >> "$GITHUB_OUTPUT"